### PR TITLE
Alpha HUD updates

### PR DESCRIPTION
**Pull request by seriesumei**
The first change here makes the alpha HUD script not care about the link order for either the buttons or the doll.

The second change adds some code to check where the HUD is attached and do a bit of position adjustments to hopefully ensure it is visible no matter where it is attached.  If the user moves the HUD it does not override that unless the HUD is attached to a new position.

These do not depend on each other but I find them both useful.  I have a copy of the HUD in my store in SL at 
http://maps.secondlife.com/secondlife/Fireheart/76/28/2099 if you want to try it out.  Of course it should also work in existing HUDs :)

### CODE REVIEW

**Comment by aiaustin** [comment]
The scriot change you are proposing ought really to be completely in your own subdirectory for now.  You appear to have modified the current release script which definitely should not be changed until a new release or release candidate made beyond RC#3.

**Comment by aiaustin** [comment]
Serei... can I also suggest that when changing any scripts you add a comment at the top near the current author line(s) to add your name and a revision date.

The appID/channel number in Shin’s scripts can (should?) stay the same unless some breaking change requires a channel number change. But if that changes a LOT of parts need to be amended not just for the release (or release candidates) but potentialiy for lots of HUD and clothing developers.

**Comment by seriesumei** [comment]
Ok, thank you Austin, it didn't look like the usual Github workflow was being used here, thanks for the explanation.  That is what I am used to so that is what I did. I will make the changes.

So are any of the other alternate versions of things being discussed?  I am still discovering things it seems every time I look somewhere...

**Comment by aiaustin** [comment]
Fred is the expert here Serie and as you saw he can take patches and pish the to master, as he did with your welcome etsta nmd fix of the ciurrenty release scripts.. which as now on the master branch. Everyone can use Git as they feel its best and hopefully Fred - in Shin's absence at the moment - will hopefully know what proposed patches can be taken into master.  Its safe anyway to commitdirectly into your own named directory and that is a good place to build up stuff that you are sharing with others to potentially contribute to a future release candidate or version.

I was just suggesting we don't change anything in "Current Release" for Ruth or Roth (expect to bring it properly in line with Shin's last version, which at the moment is the ingen-lab.com:8002 versions of Ruth RC#3 and Roth RC#1 - both of which are inconveniently no longer online but can be obtained via the versions prepared by me (and others). See https://github.com/ingen-lab/Ruth/issues/38#issuecomment-449962589

**Comment by aiaustin** [comment]
Approving the request by @seriesumei to include new Ruth HUD scripts.
Safe merge since all the added files are in a folder specific to the author.

**Comment by aiaustin** [comment]
Process wrong, reopening to "approve" rather than using mistaken "comment and close".

**Pull request merged**
